### ISSUE TITLE
Having a status property breaks the export

### ISSUE THREAD

**Issue by nerdymomocat** [innolitics/n2y#128]
Is there a way to export a page from a database that has a status property. I am not expecting it do anything more than treating it as a select property, but just being able to export without needing to delete the property.

**Comment by johndgiese** [comment]
@nerdymomocat we may not have implemented status properties yet... it should be easy to add and we'd accept a PR if you wanted to fix it. Unfortunately, this is primarily an internal tool for us and we have limited resources, so we'll fix it once we get to it.

**Comment by sHermanGriffiths** [comment]
@nerdymomocat We now do this on a regular basis, so I would assume it should work for you. Select properties are rendered as lists, I believe. Let me know if you're still having issues. I might look into it in my free time.
