### ISSUE TITLE
Ensure the order of the rows is preserved in a YAML export

### ISSUE THREAD

**Issue by johndgiese** [innolitics/n2y#16]
As best I can tell the order of the rows in the Notion database is not preserved in the generated YAML file.

**Comment by johndgiese** [comment]
@xaker00 would you expect the order of the rows in the Notion database to be preserved in the YAML file?

**Comment by xaker00** [comment]
@johndgiese  I'm not sure how Notion sends them over, but we explicitly tell `yaml.dump` not to sort the keys. https://github.com/innolitics/n2y/blob/42a8ba2aefb2267aba554f9aec5c776d49a80434/n2y/main.py#L134

API reference does not list any sorting options. https://developers.notion.com/reference/retrieve-a-database

**Comment by johndgiese** [comment]
If I understand correctly, the `sort_keys=False` means that the YAML dumper won't re-arrange the order of the columns in the original YAML database. What about the order of the rows from the database?

For example, if I dumped out the database shown in this screenshot I'd like for the entries in the generated YAML file to be in the same order as they appear in the notion database:

<img width="756" alt="Screen Shot 2022-03-28 at 9 12 21 PM" src="https://user-images.githubusercontent.com/1648754/160518770-51643d58-59ce-46c6-b6d6-2133e7a16e85.png">

Do you think that would be possible to do?

**Comment by xaker00** [comment]
It looks like Notion does not send the columns in order and there is no 'column order' property. `id` property is random except for titles, so no sorting is possible there. Unfortunately, apart from knowing what the title column is, the order is unknown in the API.

![image](https://user-images.githubusercontent.com/4360601/160676161-87aae1ec-f87f-4ea5-a4c7-2a6df9c33585.png)

**Comment by xaker00** [comment]
Sorry, I've been so obsessed with columns, that I was not reading the question correctly. I cannot find a way to get the same order as displayed in Notion.

**Comment by johndgiese** [comment]
Haha, that's okay! Wow, that's too bad there's no way to get the order of the rows as displayed in Notion. I just contacted Notion support about the issue. This is pretty unfortunate that the API works like this... it almost seems like they want to make their API useful for people who are adding data to Notion but not so useful for people who are exporting data.
