### ISSUE TITLE
Consider a library for Notion API level 

### ISSUE THREAD

**Issue by xaker00** [innolitics/n2y#17]
Instead of trying to keep up with Notion API changes and all of the nuances, consider using a library. 

- https://github.com/jamalex/notion-py
  - unofficial API
  - more features than the official API
  - not maintained lately
  - 3.5k stars
- https://github.com/ramnes/notion-sdk-py <- looks like a better choice
  - uses official API
  - actively maintained
  - 600+ stars

Not urgent, just worth considering before putting more work into the Notion API level code.

**Comment by johndgiese** [comment]
@xaker00 the two links to the libraries appear to be the same. Is the second link supposed to be https://github.com/ramnes/notion-sdk-py ?

I was considering working on this issue while also working on #23 , but then I spent some time looking at https://github.com/ramnes/notion-sdk-py, and it is quite low-level. It doesn't provide much functionality. In particular, it just exposes the same data that is exposed in the API, but we would still need to de-paginate objects, recursively get blocks, etc. I think we would also need to add our own caching mechanism at some point. Thus, I figured it may actually be simpler (and give us the most flexibility) to just keep the approach we're currently using.

In particular, checkout https://github.com/ramnes/notion-sdk-py/blob/main/notion_client/client.py#L73-L77

**Comment by xaker00** [comment]
You are correct. Stupid copy-paste error on my side. Corrected.

I created this issue to make sure we considered a library. When I wrote this, I was not sure if there would be a benefit. Looks like you have done more research in this area than I. Somewhere down the road, someone will ask why we did not use a library, and now we have a record of the decision.

**Comment by johndgiese** [comment]
It was definitely a good idea! I would have expected the library to do more than just wrap the API endpoints a bit.
