### ISSUE TITLE
Enum containment check raises TypeError for versions < 3.12

### ISSUE THREAD

**Issue by notmatthancock** [innolitics/n2y#192]
There is an [Enum containment check](https://github.com/innolitics/n2y/blob/a7ef203853fd2f62ce9124c1a41a0b59443d8ba2/n2y/notion.py#L459) which in Python versions prior to 3.11 raises a TypeError. I would suggest avoiding using the containment check so that a wider range of Python versions are supported.

**Comment by sHermanGriffiths** [comment]
@notmatthancock this is addressed in [PR #191](https://github.com/innolitics/n2y/pull/191/files)

**Comment by notmatthancock** [comment]
great, thanks!
