### ISSUE TITLE
Plan out how you will implement this; include any new command line arguments and any new dependencies you'll use

### ISSUE THREAD

**Issue by johndgiese** [innolitics/n2y#2]

**Comment by xaker00** [comment]
## Action plan
+ add get_page method to notion client (notion.py)
+ study notion api page object and come up with a way to create pandoc json from it
+ use pandoc to create markdown
+ add output location as command line argument?

## New dependencies
+ Pandoc 
	May not be strictly required, but if we have pandoc json, then generating any output is trivial, not just markdown. Better to use an existing AST than making our own.

**Comment by johndgiese** [comment]
This approach looks good to me! Could you add a few details about how you plan to test the tool? In particular, what would be the inputs and outputs for the tests? Note that we have a GitHub action that automatically runs tests when you push them up. Ideally we'd figure out some way to include our tests in there.

**Comment by xaker00** [comment]
It looks like there is already a GitHub action to run tests. I plan to add snippets of Notion page objects (in JSON) and compare to corresponding known good pandoc objects.
