### ISSUE TITLE
Support exporting sets of Notion pages and database (and preserving links between them)

### ISSUE THREAD

**Issue by johndgiese** [innolitics/n2y#24]
These requirements etc. are a work in progress ... I'm still trying to figure out how all of this fits together.

Definitions

- Notion page hierarchy - the tree structure formed with the Notion "workspace" at the root, and Notion pages and Notion database as child nodes.
- Entrypoint - Specifies a set of pages and/or databases to export into files.
- Entrypoint type - For a page, may be "single" or "recursive". For a database, may be "markdown", "yaml", or "yaml-related".
- Global configuration property - An n2y configuration property that is set globally for an invocation of n2y. (E.g., `--media-root` and `--media-url` can only be set once, as there's no apparent reason or mechanism to set the multiple times.)
- Flexible configuration property - An n2y configuration property that may be set on a per-page or per-database basis
- Selector - A string, much like a CSS selector, that is used to select pages and/or databases
- Configuration rule - A selector, along with a set of configuration properties and their values, which determine 

User Needs:

- Configuration system is simple
- Configuration system is easy to learn
- Configuration system is flexible

Requirements:

- Configuration system must support exporting the same database multiple times with multiple configurations (e.g., we sometimes want to generate a "Documents" database both as a set of markdown files AND as a YAML file with `--content-property=''`)
- Software must not download the same Notion database more than once.
- Configuration system must be able to convert the Notion page IDs into nice looking IDs.
- Configuration system must supporting generating the IDs using a simple incrementing string (e.g., SR-0001, SR-0002, ... for each page in a Software Requirements database and RI-0001, RI-0002, ... for each page in a Risks database; these ids need to be swapped out in all relationship properties.)
- Configuration system must supporting generating the IDs using one or more property values from the database (e.g., if a database has two columns that are unique together, there needs to be a way to generate a "natural key" from these two columns).
- Configuration system must support setting the --content-property and --id-property on a per database basis.

Requirements we may want to implement in the future:

- Software must treat the `--plugin` argument as a flexible configuration property.
- Configuration system must support preserving the incremental IDs between n2y invocations (e.g., using a mapping file that maps the notion page ids to our ids)

Design Ideas:

- Probably want to specify the configuration using a YAML file.
- Perhaps we can have some configuration that applies across ALL entry points, but then other configuration that can be set for just a single particular entry point.

Design Documentation:

- Write out a few example configuration YAML files.

---

Here is a write up that describes how I envision N2y working after this feature is done. It is written such that this content could be copied into the README:

---

## Mapping Notion's Datamodel to the Filesystem

A Notion workspace forms a tree datastructure with three types of nodes:

1. The "workspace" node
2. A "page" node
3. A "database" node.

The root of the tree is always a "workspace node". It's children are either databases or pages. A page has content (made up as blocks) and may have child pages and databases. A database has pages as its children. Pages whose parent is not a database only have a single "title" property. Pages whose parent is a database have extra properties, one for each column in the database.

N2y converts the Notion workspace tree, or some subtree within it, into markdown files. The properties of a page are stored as YAML frontmatter. Most of Notion's content can be represented in markdown, but not all of it. For example, toggle blocks don't have a standard representation in markdown, and neither does colors, underlining, or columns. Notion's builtin markdown export simply removes this content, but N2y provides a plugin system that allows users to customize how Notion content is converted to markdown.

The mapping between Notion and the filesystem is complicated by other differences in their datamodels.

First, all files in a directory must have unique names, but there's not a straightforward way to generate these unique names from the Notion nodes. Each node in the Notion tree _does_ have a unique id, but these ids are long and meaningless. We'd like our file names to be meaningful. Since we can't use the id, these names must be generated from page's properties. For pages in database there may be many ways to generate the name, perhaps even combining multiple properties. For pages outside a database, there is only the "title" property, and so it must be used somehow. Since page property values are not unique, duplicates must be handled somehow. It may seem that one could simply append `-2` to de-duplicate the names, but because Notion's API doesn't preserve the order of pages, these names would be unstable; sometimes one page would have the `-2` appended, while other times the other one would.

Second, unlike a directory in a filesystem that has children but no content of it's own, a Notion page does have content. This problem is solved, much as it is for websites, by placing the content of a page in a special file called `index.md`. This is a reasonable solution, but if there were a child page with the name `index`, this would also produce a name collision.

Finally, Notion nodes have a preserved order. This is clearly seen in that the order of the pages in the Notion sidebar is preserved, unlike the order of files in a directory. N2y does not attempt to preserve the order of pages, largely because Notion's API doesn't allow you to determine the order of pages in a database.

## Configuration

There are a few bits of configuration that may need to be applied to different nodes in the Notion tree:

1. What mechanism is used to generate the file name from the page's properties
2. What plugins should be applied when transforming the page's content to markdown (not all pages will necessarily want to use the same plugins)
3. Where images and files linked in the Notion pages should be placed
4. The location of the generated output files; it may be the case that someone would want to map multiple sub-trees from the Notion workspace into various different directories in a filesystem (e.g., we will want to do this when pulling various data from our company Notion over to our company website).

This configuration is all set in one single YAML file. The configuration may be applied to different parts of the tree. Maybe kind of like CSS selectors.

## Links

One of Notion's great benefits over Microsoft Word and Excel is that it allows one to easily link many related documents together. When exporting a set of pages or databases from Notion, we'd like to preserve these links and generate relative URLs as appropriate. To do this, n2y must keep an internal mapping of notion ids to their final location in the file system. Thus, it's necessary that the full n2y export be done in one big run rather than being done in multiple smaller runs. For this reason, it's necessary to handle all of the configuration for the various mappings in one file, rather than using commandline arguments.

## YAML Databases

Sometimes it is nicer to convert a database node into a single YAML file rather than into a set of markdown files in a directory. This is fine, but when you do this it is important that none of the pages in that database have subpages. If they do have subpages, there will not be any place to put them.

## Many to Many Relationships

Notion databases can link to other databases using a many-to-many relationships. (It doesn't support One-to-Many or Many-to-One). When converting these many-to-many relationships to YAML, there are a few problems:

First, since we don't want to use Notion's long and ugly ids, we need to tell Notion how to come up with a "natural key" for each of the databases. These natural keys are very likely generated the same way as the filenames will be.

Second, there are a few ways that Many-to-Many relationship could be recorded. For example, if there is a relationship between A and B, this can be encoded as:

1. a list of keys on each element in A,
2. a list of keys on each element in B, or
3. a separate file that has a list of tuples for each relation.

N2y can be configured to support all three approaches.

**Comment by johndgiese** [comment]
I'm starting to think that we should just require that each database have a mechanism to generate a "natural key". By default, we could use the value of the "title" field, but we could use some other combination of fields too. E.g., with our Articles database we use the `slug` field. We probably wouldn't want to make user's do this for _every_ database, but maybe we could let it be specified for any databases that don't just use the title. I'm also thinking, just to keep things simple, that if there ever were a duplicate, we would just error out and tell the user about it.

I think for pages that are children of another page we can depend on the order being deterministic. As a result, we can rely on the `-2`, `-3`, `-4`, ... mechanism to deal with non-unique titles. Thus, the natural key configuration would only be needed for children of a database. This same natural key mechanism could be used to record the many-to-many relationships.

Although it's possible that someone would want to generate the filenames one way and the natural keys another way, it would simplify the configuration to just require that both the filenames and the natural keys be the same.

**Comment by johndgiese** [comment]
@xaker00 I'm starting to think through how to export sets of related notion pages. I wrote out some thoughts about various technical problems in this issue. If you could read through it and let me know what you think that would be great. It may be good to jump on a call to discuss it all further.

**Comment by xaker00** [comment]
@johndgiese I think the problem is complex enough that a call makes sense.

**Comment by johndgiese** [comment]
@xaker00 absolutely! Maybe we can touch base tomorrow sometime
