### ISSUE TITLE
Add support for equations

### ISSUE THREAD

**Issue by johndgiese** [innolitics/n2y#4]
We don't currently support the "Equation" notion block type.

- [x] Make sure all unit tests are passing locally
- [x] Create a test page that has an equation
- [x] Following the instructions in the README (and using the integration key in 1password) hook up n2y to our notion page
- [x] Try converting the page to markdown using n2y; confirm that it fails because of the equation block (maybe test it with a normal page that does NOT have an equation to be sure it works on other pages)
- [x] Add support for the equation block type; in particular, you'll want to stick the raw tex into the markdown in a way that pandoc supports (see https://pandoc.org/MANUAL.html#raw-htmltex and https://pandoc.org/MANUAL.html#math)

**Comment by sHermanGriffiths** [comment]
Additions have been made and are awaiting review
