### ISSUE TITLE
Prevent filename collisions

### ISSUE THREAD

**Issue by xaker00** [innolitics/n2y#6]
Notion keeps the original filename for file blocks. Currently, n2y downloads embedded files and saves them using the original name. This could result in files being overwritten. This can be especially a problem for embedded images since they are stored in Notion as file blocks.

One solution is to name the file according to its md5 as suggested by @johndgiese.

https://github.com/innolitics/n2y/blob/998726a25a032cb7281c6cb65c211e1040ff8bd0/n2y/converter.py#L375-L390

**Comment by sHermanGriffiths** [comment]
@xaker00  The PR for `dupefileWarning` should solve this issue once approved

**Comment by johndgiese** [comment]
See https://github.com/innolitics/n2y/pull/11#issuecomment-1080696798 for more comments on this issue.

**Comment by sHermanGriffiths** [comment]
Resolved by PR #19

**Comment by johndgiese** [comment]
I believe I've implemented a solution to this that works pretty well. See https://github.com/innolitics/n2y/blob/main/n2y/notion.py#L345-L380
