### ISSUE TITLE
Move leading and trailing spaces out of bold and italic text

### ISSUE THREAD

**Issue by xaker00** [innolitics/n2y#7]
The Notion editor may include leading and trailing spaces in bold and italic formatting. A direct conversion produces markdown that is incorrect as extra spaces cause the bold and italic markup not to work with some interpreters.

Markdown produced:
```markdown
This is a **bold **word.
```
Should be;
```markdown
This is a **bold** word.
```

**Comment by johndgiese** [comment]
@sHermanGriffiths this is another good issue to work on!

**Comment by xaker00** [comment]
Addressed with PR #18
